### ISSUE TITLE
Návrh systému - GUI

### ISSUE THREAD

**Issue by magula12** [TIS2024-FMFI/realsense-game#12]
návrh používateľského rozhrania (ak projekt má GUI) - nakreslené a popísané všetky dialógy, okná a stránky, ktorými aplikácia komunikuje s používateľom - túto časť treba konzultovať so zadávateľom

**Comment by LilianaHodonova** [comment]
Po dohode so zadávateľom sme terče presunuli do veka kontajnerov. Idem zmeniť v návrhu. Mám dorobiť aj postavičky a pod do konfiguracie?
