### ISSUE TITLE
Komunikácia kamery s webom

### ISSUE THREAD

**Issue by LilianaHodonova** [TIS2024-FMFI/realsense-game#21]

**Comment by magula12** [comment]
Ak som správne pochopil, treba nájsť spôsob akým posšlem z cpp info o rychlosti a vektore do webu.
Priradujem si to .

**Comment by magula12** [comment]
# Riešenie Problému Virtuálnej Klávesnice

Vyriešil som tento problém nasledovne:

V kóde, ktorý nám bol ponúknutý, bola už použitá knižnica `windows.h`. Rozhodol som sa stavať na tejto knižnici, kde som použil typ vstupu `INPUT_KEYBOARD`. Týmto spôsobom som podobne ako v pôvodnej verzii (kde sa použil `INPUT_MOUSE` na vytvorenie "virtuálnej myši") vytvoril "virtuálnu klávesnicu".

Informácie o rýchlosti a vektore sa šifrujú nasledovne:

- **Formát**: `#S50V25,30*`
- **Význam jednotlivých častí**:
  - `#` - začiatok prenosu
  - `S` - indikuje rýchlosť
  - `V` - indikuje vektor (čiarka oddeľuje x a y komponenty vektora)
  - `*` - koniec prenosu

Prikladám .cpp súbor, ktorý bude použitý v aplikácii, a tiež HTML kód pre kolegov do JS skriptu v hre na čítanie týchto dát.
Obe v .txt verzií aby sa to sem dalo nahrať:
[con_test.txt](https://github.com/user-attachments/files/17612049/con_test.txt)
[index.txt](https://github.com/user-attachments/files/17612052/index.txt)
Printscreen z testu:
![Opera Snapshot_2024-11-03_212639_index html](https://github.com/user-attachments/assets/4c48e849-be29-4ad5-9ae1-e38fa1aa971c)
