### ISSUE TITLE
prerobenie aplikácie kamery s pridanou funkčnosťou

### ISSUE THREAD

**Issue by LilianaHodonova** [TIS2024-FMFI/realsense-game#22]

**Comment by magula12** [comment]
@LilianaHodonova môžem sa ťa spýtať ako si myslela tento issue?
Či to má zahŕňať iba samotnú implementáciu a testovanie alebo aj pripravu oboznamovanie sa a pod.  Iba kôli stage-u.  Nech sme presní. Vďaka

**Comment by LilianaHodonova** [comment]
je to napísané v návrhu, plán implementácie, prvá časť. " avšak ju obohatí o novú funkcionalitu a to o snímanie pohybu loptičky (vektor) a rýchlosť loptičky. "
