### ISSUE TITLE
Získavanie dát o rýchlosti a vektore

### ISSUE THREAD

**Issue by magula12** [TIS2024-FMFI/realsense-game#26]
Ziskanie dát o rýchlosti a vektore z projektu Wallhit_detection a napr. vypísanie do súboru.

V kóde existuje funkcia GetLastNPointsOfTrajectory - a pomocou toho by to bolo vhodné a možno aj nie najnáročnejšie zistit.

**Comment by magula12** [comment]
![Image](https://github.com/user-attachments/assets/c2422b8e-5f03-4ea6-ad85-1b000ec65d60)
Poslušne hlásim že sa mi darí získavať rýchlosť z kamery.

**Comment by magula12** [comment]
@jakubsmihula potreboval by som od teba vediet v akej forme by si potreboval vediet vektor resp poziciu lopticky, ci chces vediet x,y a z a rychlost, alebo ake data potrebujes na vizualizaciu.

**Comment by magula12** [comment]
Návrh:![115371204201366.pdf](https://github.com/user-attachments/files/17791873/115371204201366.pdf)

**Comment by magula12** [comment]
Návrh:
![PXL_20241117_182658926.MP~2.jpg](https://github.com/user-attachments/assets/496d0849-291c-498e-a5a1-af902862a33c)

**Comment by jakubsmihula** [comment]
> [@jakubsmihula](https://github.com/jakubsmihula) potreboval by som od teba vediet v akej forme by si potreboval vediet vektor resp poziciu lopticky, ci chces vediet x,y a z a rychlost, alebo ake data potrebujes na vizualizaciu.

Budeme sa snazit premietnut 3D bod do 2D tak, ze "pojdeme" po parabole v 3D priestore a premietneme ju do 2D to je zatial nejaky nacrt.

https://stackoverflow.com/questions/724219/how-to-convert-a-3d-point-into-2d-perspective-projection

**Comment by magula12** [comment]
vektor respektive trajektoria sa bude zasielat sposobom uvedenim v komentari vyssie https://github.com/TIS2024-FMFI/realsense-game/issues/26#issuecomment-2481418707

**Comment by magula12** [comment]
prebieha testovanie, implementacie a upravovanie výstupných udajov z c++
