### ISSUE TITLE
Brainstorming about the theme of the game

### ISSUE THREAD

**Issue by magula12** [TIS2024-FMFI/realsense-game#3]
We have to figure out our some themes for learning game until wednesday 10 30, when we have next meeting with Kvant.

**Comment by magula12** [comment]
Mne napadlo že poznáte tú hru respektíve tie online quizy quizlet? 
Že mohli by sme vypracovať serie kvízov z roznych tém fyzika matika geografia, historia a pod a oni budu musiet vybrat ze ktorá moznosť je spravna a podla toho budu hadzat loptou.

**Comment by LilianaHodonova** [comment]
Mne napadla idea o triedení odpadu. Budú viaceré “koše”, každý kôš bude na nejaký určitý typ odpadu (papier, plast,…). Budú sa zobrazovať objekty a loptičkou trafia kôš s farbou, pre ktorý je ten typ odpadu určený. Hra by bola určená na vzdelávanie študentov v oblasti triedenia odpadu.

**Comment by LilianaHodonova** [comment]
Slepá mapa je síce krásny nápad, ale už tretí rok sa teším, ze geografiu nemám a slepé mapy neboli moja silná stránka, teda je toto pre mňa posledná možnosť 😅

**Comment by magula12** [comment]
> Slepá mapa je síce krásny nápad, ale už tretí rok sa teším, ze geografiu nemám a slepé mapy neboli moja silná stránka, teda je toto pre mňa posledná možnosť 😅

Však ty nemusíš hádať 😅. Iba kódit.

**Comment by LilianaHodonova** [comment]
Mohlo by sa urobiť pexeso, za každou kartičkou bude 2D alebo 3D objekt a ako náučnú časť by som tam buď pod objekt pridala vzorce na výpočet obsahu a pod. alebo jeho anglický názov. Je to trochu lacná idea, ale mňa by to bavilo 😄

**Comment by LilianaHodonova** [comment]
> mne sa úprimne myšlienka tej slepej mapy páči zatiaľ najviac...

Slepú mapu rozhodne nechcem robiť. Nájdime niečo iné

**Comment by jakubsmihula** [comment]
Mne sa paci jedna memory hra. 
Na obrazovke by sa zobrazili rozne druhy predmetov. Po istom case (ktory by sa samozrejme cim dalej tym viac skracoval), by predmety zmizly a ostalo by prazdne platno. Potom by sa zobrazil obrazok, s nejakym predmetom, ktory bol na predoslom obrazku a hrac musi hodit loptu do priestoru, kde sa dany predmet nachadzal.

**Comment by jakubsmihula** [comment]
Po meetingu so zakaznikom sa dohodlo, ze aplikacia bude zamerana na triedenie rozneho druhu odpadu. Tato hra bude v 3D.
