### ISSUE TITLE
Camera calibration

### ISSUE THREAD

**Issue by jakubsmihula** [TIS2024-FMFI/realsense-game#5]
Please study documentation for camera calibration **Detekcia.docx** to dataprojector. It would be also great to try this with big wall and dataprojector.
[readme.txt](https://github.com/user-attachments/files/17283733/readme.txt)
[Detekcia.docx](https://github.com/user-attachments/files/17283736/Detekcia.docx)

Check all sections. I know it is hard since you dont have camera but it will help us with calibrating in future. 

Thanks.

**Comment by jakubsmihula** [comment]
Dohodne sa meeting na rozbehanie aplikacie. Dalsim krokom je taktiez aj pochopenie ako aplikacia funguje a nasledne jej vyuzitie v projekte. Pripadne modifikacie a podobne.

**Comment by jakubsmihula** [comment]
Odkaz na zdrojove kody od zadavatela [https://visionsystems.app.box.com/s/s1d90veulupij0ermpoabh0riepqr9db](url)

**Comment by pavelpetrovic** [comment]
Verzia, ktora sa nam podarila skompilovat: https://kempelen.dai.fmph.uniba.sk/files/realsenseCam_wallhitDetection_our_build.zip

**Comment by magula12** [comment]
Calibracia by mala byt uspesne dokoncena, ostava testovanie. Ku kluciku od miestnosti by sme sa nemali problem dostat v najblizsich dnoch. Nahodou niekto z vas nema doma taku penovu loptu alebo nieco, ja som doma nenasiel. @jakubsmihula @LilianaHodonova @podskalka1

**Comment by LilianaHodonova** [comment]
mám doma malú plastovú oranžovú loptičku (priemer asi 5cm), pohľadám ešte niečo vhodnejšie.

**Comment by magula12** [comment]
![image](https://github.com/user-attachments/assets/b64d37c2-ccb3-4746-83b3-e8db11048812)
Wallhit_Detection
source.cpp - vyzadoval zmenu v riadku 495 CV_DIST_L2 -> cv::DIST_L2 //novsia verzia

**Comment by magula12** [comment]
Projekty Calibration aj Detection, mám nastavené závislosti aj zmenené časti kódu ktoré to vyžadovali kôli novšej verzii cv.
Aktualne su fully buildable.

**Comment by magula12** [comment]
Drahý kolegovia, iba oznamujem že konečne sa mi podarilo uspesne nakalibrovat a nakonfigurovat kamerku. Takto vyzeral asi setupik, namieril som to na monitor kedze moznosti mi nedovoluju mat 10x10m stenu xD.
![462549864_1722265334980149_5801456287968748460_n](https://github.com/user-attachments/assets/f8eef55b-d42b-4855-ba23-e15197af23f2)
Hľa výsledok, program úspešne detekoval loptičku. Pri tejto vzdialenosti a veľkosti pinpongovu a v otvorenom skicári kreslil mi bodky podla kalibracie:
![image](https://github.com/user-attachments/assets/9092aef5-2f6f-4223-89d4-049c2a2bef5f)
Moje ďaľšie kroky vedú k bližším poznaním sa z programom nájsť miesto kde by som mohol vyčítať vektor a rýchlosť. A zároveň aj oboznaámenie sa z technológiou posielanie takýchto dát na web.
