### ISSUE TITLE
Katalóg požiadaviek

### ISSUE THREAD

**Issue by LilianaHodonova** [TIS2024-FMFI/realsense-game#6]
vytvoriť katalóg požiadaviek po stretnutí s KVANTom.

**Comment by magula12** [comment]
Robim review čiastočnej vericie: @LilianaHodonova nechyba nam tam nejaka priorita tych poziadaviek?

**Comment by magula12** [comment]
Aaa mozno trochu bug v 3.4.6b - zee je tam že po hodeni lopticky hocikam sa hra zacne odznova, aaale ja by som tam pridal ze iba 5 sek potom sa hra vrati do config verzie. Lebo inac by sme zostali zaseknuty na tom ze sa neda bez refreshu zmenit hra

**Comment by magula12** [comment]
potom 3.4.5a - som upravil formát na "m:ss" m- minuty s-sekundy, je to popisnejsie. Moze byt?

**Comment by magula12** [comment]
Update aj 3.4.4 a 3.4.6 pre prípad anglického jazyka
Zároveň sa obávam že 3.4.6 môže byť vyhodnotená ako neatomická. Prosím o feedback.
3.5 je dokončená
Prosím o kontrolu.

**Comment by LilianaHodonova** [comment]
Ok súhlasím, prerob potrebné. Skontrolujem neskor, teraz to pri sebe nemám

**Comment by magula12** [comment]
upravil som viacero podľa mňa neatomických podmienok v kapitole 3.4, tak skuste skontrolovať či som nepokazil niečo

**Comment by LilianaHodonova** [comment]
Prečítala som to, za mňa je to super :)

**Comment by magula12** [comment]
Last Update. Pridal som poziadavky ze admin a vytvaranie novych prihlasovaciek, ale kedze veci co som myslel ja skor boli povedane ze to mozme spravit tak to tam nedam ako podmienku. 
Prosím o last check nech to mozem odoslat na kontrolu. Dakujem

**Comment by LilianaHodonova** [comment]
Je to ok, môžeš poslať na kontrolu

**Comment by LilianaHodonova** [comment]
S @podskalka1 sme prešli a prerobili katalóg, je tam pár komentárov, budem rada, ak sa na to pozriete a dorobíte to. @magula12 @jakubsmihula

**Comment by magula12** [comment]
> S @podskalka1 sme prešli a prerobili katalóg, je tam pár komentárov, budem rada, ak sa na to pozriete a dorobíte to. @magula12 @jakubsmihula

okej

**Comment by magula12** [comment]
https://docs.google.com/document/d/1ahkAwWUORdbXcBoaVyn0zplK1nFElml3/edit

**Comment by LilianaHodonova** [comment]
Dorobila som požiadavky od zadávateľa. Poprosím o rýchly check, či som niečo nezabudla. Ďakujem

**Comment by magula12** [comment]
Vyborne, skontrolované a otazku katalogu povazujem za vybavenu.
