### ISSUE TITLE
Game configuration

### ISSUE THREAD

**Issue by magula12** [TIS2024-FMFI/realsense-game#7]
@LilianaHodonova ahoj pocuj chcel som sa ta spytat k tej konfigurácii hry, nemyslim si ze je dobry napad, respektíve ze to nemysleli tak ze konfiguraciu hry treba ovladat loptickou

**Comment by LilianaHodonova** [comment]
Tak to ti neviem povedať. My sme s Kubom mysleli že takto by to bolo fajn aj na nejaké evanty. Vieš ak sa napríklad budú rýchlo striedať tak toto bude lepšie.

**Comment by magula12** [comment]
ze v config hry by som dal nejake checkboxy alebo radiobuttons ze jak chces nastavit tu hry spustis hru odrata sa 5 sek a ides

**Comment by LilianaHodonova** [comment]
No ale keď to dajú do múzea a skončí ze hra a budú chcieť aby zase išlo tak to budú stále musieť myšou nastavovať?

**Comment by magula12** [comment]
dobra otazka...

> No ale keď to dajú do múzea a skončí ze hra a budú chcieť aby zase išlo tak to budú stále musieť myšou nastavovať?

**Comment by LilianaHodonova** [comment]
Myslím si že naprogramovať jednu alebo druhu časť nie je taký problém, len sa dohodnúť

**Comment by magula12** [comment]
mozno ze zacat odznova by tam bolo len ci?

**Comment by LilianaHodonova** [comment]
No a keď prídeš do múzea sám a pred tebou hrali dvaja, tak si moc nezahráš

**Comment by magula12** [comment]
good point


> No a keď prídeš do múzea sám a pred tebou hrali dvaja, tak si moc nezahráš

**Comment by magula12** [comment]
okay nechajme to takto mate pravdu, vdaka za diskusiu xD. Zatváram issue.
